/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */


public void BeginPressed(GButton source, GEvent event) { //_CODE_:Begin:240269:
   stats = loadTable("stats.csv","header");
 g=3;
} //_CODE_:Begin:240269:

public void EndPressed(GButton source, GEvent event) { //_CODE_:End:422375:
 int d = day();
 int m=month();
 int y = year();
 String date = m + "-" + d + "-" + y;
 TableRow newR = stats.addRow();
 newR.setString("date", date);
 saveTable(stats, "stats.csv");
  
} //_CODE_:End:422375:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  Begin = new GButton(this, 18, 289, 80, 30);
  Begin.setText("Begin");
  Begin.addEventHandler(this, "BeginPressed");
  End = new GButton(this, 396, 287, 80, 30);
  End.setText("Done");
  End.addEventHandler(this, "EndPressed");
}

// Variable declarations 
// autogenerated do not edit
GButton Begin; 
GButton End; 